version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein uberjar
      - run: lein test
      - run: |
          lein cloverage --codecov
          bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
  deploy:
    docker:
      - image: circleci/clojure
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      GRAALVM_HOME: /home/circleci/repo/.graalvm

    steps:
      - add_ssh_keys:
          fingerprints:
            - "c2:6b:15:e5:de:8e:13:7a:f8:b1:87:02:2d:94:a3:f9"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run:
          name: Install GraalVM
          command: |
            curl -O -J -L https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-23.0.1/graalvm-community-jdk-23.0.1_linux-x64_bin.tar.gz
            tar xfz graalvm-community-jdk-23.0.1_linux-x64_bin.tar.gz
            mv graalvm-community-openjdk-23.0.1+11.1 $GRAALVM_HOME
            rm graalvm-community-jdk-23.0.1_linux-x64_bin.tar.gz
      - run: sudo apt-get update && sudo apt-get install -y leiningen build-essential libz-dev
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein uberjar
      - run: lein native-image
      - run: |
          ssh-keyscan -H pastespace.org >> ~/.ssh/known_hosts
          scp -o StrictHostKeyChecking=no target/uberjar/bayaz-0.1.0-SNAPSHOT-standalone.jar bayaz@pastespace.org:jar/bayaz-$CIRCLE_SHA1.jar
          scp -o StrictHostKeyChecking=no target/default+native-image/bayaz bayaz@pastespace.org:bin/bayaz-$CIRCLE_SHA1
          ssh -o StrictHostKeyChecking=no bayaz@pastespace.org "./deploy-changes bayaz-$CIRCLE_SHA1.jar"

workflows:
  build:
    unless:
      matches:
        pattern: "^prod$"
        value: << pipeline.git.branch >>
    jobs:
      - build
  deploy:
    when:
      matches:
        pattern: "^prod$"
        value: << pipeline.git.branch >>
    jobs:
      - deploy
