# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.5
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein uberjar
      - run: lein test
      - run: |
          lein cloverage --codecov
          bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
  deploy:
    docker:
      - image: circleci/clojure:lein-2.9.5
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein uberjar
      - run: |
          scp target/uberjar/bayaz-0.1.0-SNAPSHOT-standalone.jar bayaz@pastespace.org:jar/bayaz-$CIRCLE_SHA1.jar
          ssh bayaz@pastespace.org -c "./deploy-changes bayaz-$CIRCLE_SHA1.jar"

workflows:
  build:
    jobs:
      - build
        filters:
          branches:
            ignore:
              - prod
  deploy:
    jobs:
      - deploy
        filters:
          branches:
            only:
              - prod
