version: 2.1

jobs:
  build:
    docker:
      - image: cimg/clojure:1.11.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein uberjar
      - run: lein test
      - run: |
          lein cloverage --codecov
          bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
  deploy:
    docker:
      - image: circleci/clojure:lein-2.9.5
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"

    steps:
      - add_ssh_keys:
          fingerprints:
            - "c2:6b:15:e5:de:8e:13:7a:f8:b1:87:02:2d:94:a3:f9"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein uberjar
      - run: |
          ssh-keyscan -H pastespace.org >> ~/.ssh/known_hosts
          scp -o StrictHostKeyChecking=no target/uberjar/bayaz-0.1.0-SNAPSHOT-standalone.jar bayaz@pastespace.org:jar/bayaz-$CIRCLE_SHA1.jar
          ssh -o StrictHostKeyChecking=no bayaz@pastespace.org "./deploy-changes bayaz-$CIRCLE_SHA1.jar"

workflows:
  build:
    unless:
      matches:
        pattern: "^prod$"
        value: << pipeline.git.branch >>
    jobs:
      - build
  deploy:
    when:
      matches:
        pattern: "^prod$"
        value: << pipeline.git.branch >>
    jobs:
      - deploy
