version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein uberjar
      - run: lein test
      - run: |
          lein cloverage --codecov
          bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

workflows:
  build:
    jobs:
      - build
